export const INCREASE_RATING = "INCREASE_RATING";
export const DECREASE_RATING = "DECREASE_RATING";
export const SET_VALUE = "SET_VALUE";
export const SET_RATING_RIGHT = "SET_RATING_RIGHT";
export const SET_IS_AUTH = "SET_IS_AUTH";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
